export const MODO_JUEGO = "MODO_JUEGO";
export const JUGADA_SELECCIONADA = "JUGADA_SELECCIONADA";
export const REINICIAR_JUEGO = "REINICIAR_JUEGO";
export const GANO_JUGADOR_UNO_VS_MAQUINA = "GANO_JUGADOR_UNO_VS_MAQUINA";