export const MODO_JUEGO = "MODO_JUEGO";
export const JUGADA_SELECCIONADA = "JUGADA_SELECCIONADA";
export const REINICIAR_JUEGO = "REINICIAR_JUEGO";
export const GANO_JUGADOR_UNO_VS_MAQUINA = "GANO_JUGADOR_UNO_VS_MAQUINA";
export const EMPATE_VS_MAQUINA = "EMPATE_VS_MAQUINA";
export const JUGADA_MAQUINA = "JUGADA_MAQUINA";
export const DESCRIPCION_VICTORIA = "DESCRIPCION_VICTORIA";
export const JUGADA_SELECCIONADA_JUGADOR_DOS = "JUGADA_SELECCIONADA_JUGADOR_DOS";