export const JUGADA = {
  LAGARTO: "LAGARTO",
  TIJERA: "TIJERA",
  PIEDRA: "PIEDRA",
  SPOCK: "SPOCK",
  PAPEL: "PAPEL",
};

export const MODO = {
  JUGADOR_UNO: "JUGADOR_UNO",
  JUGADOR_DOS: "JUGADOR_DOS",
};
